id: PD4F5C469
initial_creation_type: input
source_metadata:
  title: Record of Teachings Received by Gong dkar Phrin las rnam rgyals (17th cent.)
  author: gong dkar phrin las rnam rgyal/
  description: 'Digital version 2.0 {Wylie}; WYLIE COPY of master xml (completed:
    2020-01-18); no thematic TEI markup'
  source: https://sakyaresearch.org
  file_info:
  - 'Language: Wylie'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:Sakya Research Centre; This text was published by the rDzong pa'i
    dpe rnying 'tshol bsdu khang. (src)
  - Text input:rdzong pa'i dpe rnying 'tshol bsdu khang / (Tibet) (dpn)
  - Editorial process:Mathias Fermer (mf)
  - TEI Encoding:Sakya Research Centre
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/3131
  bases:
    5e8b:
      title: Record of Teachings Received by Gong dkar Phrin las rnam rgyals (17th
        cent.)
      order: 1
      base_file: 5e8b.txt
created_at: '2022-04-15T19:07:55.821863'
last_modified_at: '2022-04-15T19:07:55.821871'
quality: null
